// API Configuration
export const API_BASE_URL = 'http://localhost:3000/v1';

export const API_ENDPOINTS = {
  // Auth
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    ME: '/auth/me'
  },
  
  // Venues
  VENUES: {
    LIST: '/venues',
    DETAIL: (id: string) => `/venues/${id}`,
    AVAILABILITY: (id: string) => `/venues/${id}/availability`,
    CREATE: '/venues',
    UPDATE: (id: string) => `/venues/${id}`,
    PHOTOS: (id: string) => `/venues/${id}/photos`,
    DELETE: (id: string) => `/venues/${id}`,
    STATUS: (id: string) => `/venues/${id}/status`
  },
  
  // Mobile Providers
  MOBILE_PROVIDERS: {
    LIST: '/mobile-providers',
    DETAIL: (id: string) => `/mobile-providers/${id}`,
    AVAILABILITY: (id: string) => `/mobile-providers/${id}/availability`,
    CREATE: '/mobile-providers',
    UPDATE: (id: string) => `/mobile-providers/${id}`,
    STATUS: (id: string) => `/mobile-providers/${id}/status`
  },
  
  // Services
  SERVICES: {
    VENUE_SERVICES: (venueId: string) => `/venues/${venueId}/services`,
    ADD_SERVICE: (venueId: string) => `/venues/${venueId}/services`,
    UPDATE_SERVICE: (venueId: string, serviceId: string) => `/venues/${venueId}/services/${serviceId}`,
    DELETE_SERVICE: (venueId: string, serviceId: string) => `/venues/${venueId}/services/${serviceId}`,
    MOBILE_PROVIDER_SERVICES: (providerId: string) => `/mobile-providers/${providerId}/services`
  },
  
  // Staff
  STAFF: {
    LIST: (venueId: string) => `/venues/${venueId}/staff`,
    INVITE: (venueId: string) => `/venues/${venueId}/staff/invite`,
    ACCEPT_INVITE: '/staff/accept-invite',
    AVAILABILITY: (staffId: string) => `/staff/${staffId}/availability`,
    DELETE: (venueId: string, staffId: string) => `/venues/${venueId}/staff/${staffId}`
  },
  
  // Bookings
  BOOKINGS: {
    LIST: '/bookings',
    DETAIL: (id: string) => `/bookings/${id}`,
    CREATE: '/bookings',
    CONFIRM: (id: string) => `/bookings/${id}/confirm`,
    CANCEL: (id: string) => `/bookings/${id}/cancel`,
    COMPLETE: (id: string) => `/bookings/${id}/complete`,
    NO_SHOW: (id: string) => `/bookings/${id}/no-show`
  },
  
  // Reviews
  REVIEWS: {
    LIST: (venueId: string) => `/venues/${venueId}/reviews`,
    CREATE: '/reviews',
    DELETE: (id: string) => `/reviews/${id}`
  },
  
  // Admin
  ADMIN: {
    PENDING: '/admin/pending',
    USERS: '/admin/users',
    BOOKINGS: '/admin/bookings',
    BAN_USER: (id: string) => `/admin/users/${id}/ban`
  }
};

// App Configuration
export const APP_CONFIG = {
  NAME: 'ZANA',
  VERSION: '1.0.0',
  THEME: {
    PRIMARY: '#1A56DB', // Blue
    PRIMARY_DARK: '#1E40AF',
    WHITE: '#FFFFFF',
    GRAY_50: '#F9FAFB',
    GRAY_100: '#F3F4F6',
    GRAY_200: '#E5E7EB',
    GRAY_300: '#D1D5DB',
    GRAY_400: '#9CA3AF',
    GRAY_500: '#6B7280',
    GRAY_600: '#4B5563',
    GRAY_700: '#374151',
    GRAY_800: '#1F2937',
    GRAY_900: '#111827',
    RED_500: '#EF4444',
    GREEN_500: '#22C55E',
    YELLOW_500: '#F59E0B',
    BLUE_500: '#3B82F6',
    INDIGO_500: '#6366F1'
  },
  FONTS: {
    REGULAR: 'System',
    SEMI_BOLD: 'System',
    BOLD: 'System'
  },
  DIMENSIONS: {
    TOUCH_TARGET: 44, // Minimum touch target size in pixels
    BORDER_RADIUS: 8,
    SPACING: {
      XS: 4,
      SM: 8,
      MD: 16,
      LG: 24,
      XL: 32
    }
  },
  VALIDATION: {
    PASSWORD_MIN_LENGTH: 6,
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 50,
    PHONE_MIN_LENGTH: 10,
    PHONE_MAX_LENGTH: 15,
    DESCRIPTION_MAX_LENGTH: 500
  }
};

// Navigation Routes
export const ROUTES = {
  // Auth Routes
  SPLASH: '/',
  ONBOARDING: '/onboarding',
  LOGIN: '/(auth)/login',
  REGISTER: '/(auth)/register',
  FORGOT_PASSWORD: '/(auth)/forgot-password',
  RESET_PASSWORD: '/(auth)/reset-password',
  
  // Main App Routes
  HOME: '/(tabs)/home',
  SEARCH: '/(tabs)/search',
  APPOINTMENTS: '/(tabs)/appointments',
  ACCOUNT: '/(tabs)/account',
  
  // Booking Flow
  BOOKING_SERVICE: '/booking/service',
  BOOKING_STAFF: '/booking/staff',
  BOOKING_DATETIME: '/booking/datetime',
  BOOKING_CONFIRM: '/booking/confirm',
  BOOKING_SUCCESS: '/booking/success',
  
  // Detail Routes
  VENUE_DETAIL: '/venue/[id]',
  PROVIDER_DETAIL: '/provider/[id]',
  BOOKING_DETAIL: '/appointments/[id]',
  
  // Provider App Routes
  PROVIDER_ONBOARDING: '/onboarding',
  PROVIDER_DASHBOARD: '/(tabs)/dashboard',
  PROVIDER_CALENDAR: '/(tabs)/calendar',
  PROVIDER_SERVICES: '/(tabs)/services',
  PROVIDER_TEAM: '/(tabs)/team',
  PROVIDER_ACCOUNT: '/(tabs)/account',
  PROVIDER_BOOKING_REQUEST: '/bookings/[id]',
  PROVIDER_BOOKING_DETAIL: '/bookings/[id]/detail'
};

// Storage Keys
export const STORAGE_KEYS = {
  AUTH_TOKENS: 'zana_auth_tokens',
  USER_PROFILE: 'zana_user_profile',
  ONBOARDING_COMPLETED: 'zana_onboarding_completed',
  PUSH_TOKEN: 'zana_push_token',
  APP_LANGUAGE: 'zana_app_language'
};

// Zambia-specific constants
export const ZAMBIA_CONFIG = {
  COUNTRY_CODE: '+260',
  REGIONS: [
    'Lusaka',
    'Copperbelt',
    'Southern',
    'Northern',
    'Eastern',
    'Western',
    'North-Western',
    'Luapula',
    'Muchinga',
    'Central'
  ],
  CITIES: [
    'Lusaka',
    'Kitwe',
    'Ndola',
    'Livingstone',
    'Kabwe',
    'Chipata',
    'Chingola',
    'Mufulira',
    'Luanshya',
    'Solwezi'
  ],
  CURRENCY: {
    SYMBOL: 'K',
    CODE: 'ZMW',
    NAME: 'Zambian Kwacha'
  },
  PHONE_REGEX: /^[0-9]{10,15}$/,
  TIMEZONE: 'Africa/Lusaka',
  DEFAULT_LOCATION: {
    latitude: -15.4089,
    longitude: 28.2815
  }
};

// Service categories
export const SERVICE_CATEGORIES = [
  { key: 'HAIRCUT', label: 'Haircut', icon: 'scissors' },
  { key: 'HAIR_STYLING', label: 'Hair Styling', icon: 'brush' },
  { key: 'BRAIDING', label: 'Braiding', icon: 'braid' },
  { key: 'LOCS', label: 'Locs', icon: 'hair-dryer' },
  { key: 'WEAVE', label: 'Weave', icon: 'hair-dryer' },
  { key: 'BEARD_TRIM', label: 'Beard Trim', icon: 'face-mask' },
  { key: 'SHAVE', label: 'Shave', icon: 'razor' },
  { key: 'NAILS', label: 'Nails', icon: 'fingernail' },
  { key: 'MAKEUP', label: 'Makeup', icon: 'makeup-brush' },
  { key: 'EYEBROWS', label: 'Eyebrows', icon: 'eye' }
];

// Venue categories
export const VENUE_CATEGORIES = [
  { key: 'SALON', label: 'Hair Salon', icon: 'scissors' },
  { key: 'BARBERSHOP', label: 'Barbershop', icon: 'razor' },
  { key: 'NAIL_STUDIO', label: 'Nail Studio', icon: 'fingernail' },
  { key: 'MAKEUP_STUDIO', label: 'Makeup Studio', icon: 'makeup-brush' }
];

// Booking statuses
export const BOOKING_STATUSES = {
  PENDING: { key: 'PENDING', label: 'Pending', color: '#F59E0B' },
  CONFIRMED: { key: 'CONFIRMED', label: 'Confirmed', color: '#3B82F6' },
  IN_PROGRESS: { key: 'IN_PROGRESS', label: 'In Progress', color: '#6366F1' },
  COMPLETED: { key: 'COMPLETED', label: 'Completed', color: '#22C55E' },
  CANCELLED: { key: 'CANCELLED', label: 'Cancelled', color: '#EF4444' },
  NO_SHOW: { key: 'NO_SHOW', label: 'No Show', color: '#6B7280' }
};

// Service modes
export const SERVICE_MODES = [
  { key: 'SALON_VISIT', label: 'Salon Visit', icon: 'building' },
  { key: 'BARBERSHOP_VISIT', label: 'Barbershop Visit', icon: 'shop' },
  { key: 'MOBILE', label: 'Mobile Service', icon: 'car' }
];

// Time slots configuration
export const TIME_CONFIG = {
  SLOT_DURATION: 30, // minutes
  START_HOUR: 8, // 8 AM
  END_HOUR: 18, // 6 PM
  BOOKING_LEAD_TIME: 60, // minutes before which booking is not allowed
  CANCELLATION_DEADLINE: 120 // minutes before which cancellation is allowed
};

// Map configuration
export const MAP_CONFIG = {
  DEFAULT_ZOOM: 15,
  MAX_ZOOM: 20,
  MIN_ZOOM: 10,
  DEFAULT_RADIUS: 10, // km
  MAX_RADIUS: 50, // km
  MIN_RADIUS: 1, // km
  PIN_COLORS: {
    VENUE: '#1A56DB',
    MOBILE: '#F59E0B'
  }
};

// Push notification topics
export const NOTIFICATION_TOPICS = {
  BOOKING_UPDATES: 'booking-updates',
  PROMOTIONS: 'promotions',
  REMINDERS: 'reminders',
  GENERAL: 'general'
};

// Error messages
export const ERROR_MESSAGES = {
  NETWORK_ERROR: 'Network error. Please check your connection.',
  SERVER_ERROR: 'Server error. Please try again later.',
  UNAUTHORIZED: 'You need to log in to access this feature.',
  FORBIDDEN: 'You do not have permission to access this feature.',
  NOT_FOUND: 'The requested resource was not found.',
  VALIDATION_ERROR: 'Please check your input and try again.',
  EMAIL_EXISTS: 'An account with this email already exists.',
  PHONE_EXISTS: 'An account with this phone number already exists.',
  INVALID_CREDENTIALS: 'Invalid email/phone or password.',
  TOKEN_EXPIRED: 'Your session has expired. Please log in again.',
  BOOKING_UNAVAILABLE: 'This time slot is no longer available.',
  BOOKING_NOT_FOUND: 'Booking not found.',
  VENUE_NOT_FOUND: 'Venue not found.',
  SERVICE_NOT_FOUND: 'Service not found.',
  STAFF_NOT_FOUND: 'Staff member not found.',
  PROVIDER_NOT_FOUND: 'Provider not found.',
  REVIEW_ALREADY_EXISTS: 'You have already reviewed this booking.',
  BOOKING_ALREADY_COMPLETED: 'This booking has already been completed.',
  BOOKING_ALREADY_CANCELLED: 'This booking has already been cancelled.',
  BOOKING_ALREADY_CONFIRMED: 'This booking has already been confirmed.',
  BOOKING_TOO_LATE: 'Cannot cancel booking. Too close to appointment time.',
  INVALID_ROLE: 'Invalid user role.',
  ACCOUNT_SUSPENDED: 'Your account has been suspended.',
  VENUE_PENDING_APPROVAL: 'This venue is pending admin approval.',
  PROVIDER_PENDING_APPROVAL: 'This provider is pending admin approval.',
  NO_INTERNET: 'No internet connection available.',
  LOCATION_PERMISSION_DENIED: 'Location permission denied. Please enable location services.',
  LOCATION_UNAVAILABLE: 'Location services are unavailable.',
  IMAGE_UPLOAD_FAILED: 'Failed to upload image. Please try again.',
  INVALID_IMAGE: 'Invalid image format. Please select a valid image file.',
  IMAGE_TOO_LARGE: 'Image is too large. Please select a smaller file.',
  BOOKING_FAILED: 'Failed to create booking. Please try again.',
  PAYMENT_FAILED: 'Payment failed. Please try again.',
  PAYMENT_CANCELLED: 'Payment cancelled.',
  INVALID_PHONE: 'Please enter a valid phone number.',
  INVALID_EMAIL: 'Please enter a valid email address.',
  PASSWORD_TOO_SHORT: 'Password must be at least 6 characters long.',
  NAME_TOO_SHORT: 'Name must be at least 2 characters long.',
  DESCRIPTION_TOO_LONG: 'Description is too long.',
  SERVICE_UNAVAILABLE: 'This service is currently unavailable.',
  STAFF_UNAVAILABLE: 'This staff member is not available at the selected time.',
  PROVIDER_UNAVAILABLE: 'This provider is not available at the selected time.',
  VENUE_CLOSED: 'This venue is closed at the selected time.',
  INVALID_DATE: 'Please select a valid date.',
  PAST_DATE: 'Cannot book appointments in the past.',
  INVALID_TIME: 'Please select a valid time.',
  INVALID_RADIUS: 'Please enter a valid service radius.',
  INVALID_PRICE: 'Please enter a valid price.',
  INVALID_DURATION: 'Please enter a valid duration.',
  INVALID_RATING: 'Please provide a valid rating.',
  COMMENT_TOO_LONG: 'Comment is too long.',
  REVIEW_FAILED: 'Failed to submit review. Please try again.',
  NOTIFICATION_FAILED: 'Failed to send notification.',
  EMAIL_SEND_FAILED: 'Failed to send email.',
  SMS_SEND_FAILED: 'Failed to send SMS.',
  PUSH_SEND_FAILED: 'Failed to send push notification.',
  INVITE_FAILED: 'Failed to send invite.',
  INVITE_EXPIRED: 'Invite has expired.',
  INVITE_DECLINED: 'Invite has been declined.',
  FOLLOW_FAILED: 'Failed to follow.',
  UNFOLLOW_FAILED: 'Failed to unfollow.',
  LIKE_FAILED: 'Failed to like.',
  UNLIKE_FAILED: 'Failed to unlike.',
  SHARE_FAILED: 'Failed to share.',
  DOWNLOAD_FAILED: 'Failed to download.',
  UPLOAD_FAILED: 'Failed to upload.',
  SAVE_FAILED: 'Failed to save.',
  DELETE_FAILED: 'Failed to delete.',
  ARCHIVE_FAILED: 'Failed to archive.',
  RESTORE_FAILED: 'Failed to restore.',
  DUPLICATE_FAILED: 'Failed to duplicate.',
  EXPORT_FAILED: 'Failed to export.',
  IMPORT_FAILED: 'Failed to import.',
  SYNC_FAILED: 'Failed to sync.',
  BACKUP_FAILED: 'Failed to backup.',
  RESTORE_FROM_BACKUP_FAILED: 'Failed to restore from backup.',
  UPDATE_FAILED: 'Failed to update.',
  FEATURE_DISABLED: 'This feature is disabled.',
  THEME_CHANGE_FAILED: 'Failed to change theme.',
  LANGUAGE_CHANGE_FAILED: 'Failed to change language.',
  CURRENCY_CHANGE_FAILED: 'Failed to change currency.',
  REGION_CHANGE_FAILED: 'Failed to change region.',
  TIMEZONE_CHANGE_FAILED: 'Failed to change timezone.',
  NOTIFICATION_SETTINGS_UPDATE_FAILED: 'Failed to update notification settings.',
  PRIVACY_SETTINGS_UPDATE_FAILED: 'Failed to update privacy settings.',
  SECURITY_SETTINGS_UPDATE_FAILED: 'Failed to update security settings.',
  ACCOUNT_SETTINGS_UPDATE_FAILED: 'Failed to update account settings.',
  APP_SETTINGS_UPDATE_FAILED: 'Failed to update app settings.',
  FEEDBACK_SUBMITTED_FAILED: 'Failed to submit feedback.',
  REPORT_SUBMITTED_FAILED: 'Failed to submit report.',
  SUPPORT_TICKET_CREATION_FAILED: 'Failed to create support ticket.',
  SUPPORT_TICKET_UPDATE_FAILED: 'Failed to update support ticket.',
  SUPPORT_TICKET_CLOSURE_FAILED: 'Failed to close support ticket.',
  FAQ_VIEW_FAILED: 'Failed to view FAQ.',
  TUTORIAL_COMPLETION_FAILED: 'Failed to complete tutorial.',
  ONBOARDING_COMPLETION_FAILED: 'Failed to complete onboarding.',
  PROMOTION_APPLY_FAILED: 'Failed to apply promotion.',
  COUPON_APPLY_FAILED: 'Failed to apply coupon.',
  DISCOUNT_APPLY_FAILED: 'Failed to apply discount.',
  REWARD_EARNING_FAILED: 'Failed to earn reward.',
  LEVEL_UP_FAILED: 'Failed to level up.',
  BADGE_EARNING_FAILED: 'Failed to earn badge.',
  ACHIEVEMENT_UNLOCK_FAILED: 'Failed to unlock achievement.',
  MILESTONE_REACH_FAILED: 'Failed to reach milestone.',
  GOAL_ACHIEVEMENT_FAILED: 'Failed to achieve goal.',
  CHALLENGE_COMPLETION_FAILED: 'Failed to complete challenge.',
  STREAK_CONTINUATION_FAILED: 'Failed to continue streak.',
  RECORD_BREAK_FAILED: 'Failed to break record.',
  PERSONAL_BEST_FAILED: 'Failed to achieve personal best.',
  FIRST_TIME_FAILED: 'Failed to complete first time action.',
  WELCOME_BACK_FAILED: 'Failed to welcome back.',
  THANK_YOU_FAILED: 'Failed to say thank you.',
  APPRECIATION_FAILED: 'Failed to show appreciation.',
  LOYALTY_REWARD_FAILED: 'Failed to reward loyalty.',
  REFERRAL_FAILED: 'Failed to refer.',
  FRIEND_JOIN_FAILED: 'Failed to join friend.',
  GROUP_CREATION_FAILED: 'Failed to create group.',
  GROUP_JOIN_FAILED: 'Failed to join group.',
  GROUP_LEAVE_FAILED: 'Failed to leave group.',
  GROUP_DELETION_FAILED: 'Failed to delete group.',
  CHAT_START_FAILED: 'Failed to start chat.',
  MESSAGE_SEND_FAILED: 'Failed to send message.',
  MESSAGE_DELETION_FAILED: 'Failed to delete message.',
  CONVERSATION_ARCHIVE_FAILED: 'Failed to archive conversation.',
  CONVERSATION_UNARCHIVE_FAILED: 'Failed to unarchive conversation.',
  USER_BLOCK_FAILED: 'Failed to block user.',
  USER_UNBLOCK_FAILED: 'Failed to unblock user.',
  USER_REPORT_FAILED: 'Failed to report user.',
  USER_MUTE_FAILED: 'Failed to mute user.',
  USER_UNMUTE_FAILED: 'Failed to unmute user.',
  MESSAGE_PIN_FAILED: 'Failed to pin message.',
  MESSAGE_UNPIN_FAILED: 'Failed to unpin message.',
  MESSAGE_STAR_FAILED: 'Failed to star message.',
  MESSAGE_UNSTAR_FAILED: 'Failed to unstar message.',
  REACTION_ADD_FAILED: 'Failed to add reaction.',
  REACTION_REMOVE_FAILED: 'Failed to remove reaction.',
  EMOJI_ADD_FAILED: 'Failed to add emoji.',
  EMOJI_REMOVE_FAILED: 'Failed to remove emoji.',
  STICKER_ADD_FAILED: 'Failed to add sticker.',
  STICKER_REMOVE_FAILED: 'Failed to remove sticker.',
  GIF_SEND_FAILED: 'Failed to send GIF.',
  FILE_SEND_FAILED: 'Failed to send file.',
  VOICE_MESSAGE_SEND_FAILED: 'Failed to send voice message.',
  VIDEO_CALL_START_FAILED: 'Failed to start video call.',
  VIDEO_CALL_END_FAILED: 'Failed to end video call.',
  AUDIO_CALL_START_FAILED: 'Failed to start audio call.',
  AUDIO_CALL_END_FAILED: 'Failed to end audio call.',
  SCREEN_SHARE_START_FAILED: 'Failed to start screen share.',
  SCREEN_SHARE_END_FAILED: 'Failed to end screen share.',
  RECORDING_START_FAILED: 'Failed to start recording.',
  RECORDING_END_FAILED: 'Failed to end recording.',
  LIVE_STREAM_START_FAILED: 'Failed to start live stream.',
  LIVE_STREAM_END_FAILED: 'Failed to end live stream.',
  BROADCAST_START_FAILED: 'Failed to start broadcast.',
  BROADCAST_END_FAILED: 'Failed to end broadcast.',
  EVENT_CREATION_FAILED: 'Failed to create event.',
  EVENT_UPDATE_FAILED: 'Failed to update event.',
  EVENT_DELETION_FAILED: 'Failed to delete event.',
  EVENT_JOIN_FAILED: 'Failed to join event.',
  EVENT_LEAVE_FAILED: 'Failed to leave event.',
  EVENT_CANCELLATION_FAILED: 'Failed to cancel event.',
  EVENT_RESCHEDULE_FAILED: 'Failed to reschedule event.',
  REMINDER_ADD_FAILED: 'Failed to add reminder.',
  REMINDER_UPDATE_FAILED: 'Failed to update reminder.',
  REMINDER_DELETION_FAILED: 'Failed to delete reminder.',
  REMINDER_COMPLETION_FAILED: 'Failed to complete reminder.',
  TASK_CREATION_FAILED: 'Failed to create task.',
  TASK_UPDATE_FAILED: 'Failed to update task.',
  TASK_DELETION_FAILED: 'Failed to delete task.',
  TASK_COMPLETION_FAILED: 'Failed to complete task.',
  TASK_ASSIGNMENT_FAILED: 'Failed to assign task.',
  TASK_UNASSIGNMENT_FAILED: 'Failed to unassign task.',
  PROJECT_CREATION_FAILED: 'Failed to create project.',
  PROJECT_UPDATE_FAILED: 'Failed to update project.',
  PROJECT_DELETION_FAILED: 'Failed to delete project.',
  PROJECT_COMPLETION_FAILED: 'Failed to complete project.',
  PROJECT_ARCHIVING_FAILED: 'Failed to archive project.',
  PROJECT_RESTORED_FAILED: 'Failed to restore project.',
  TEAM_CREATION_FAILED: 'Failed to create team.',
  TEAM_UPDATE_FAILED: 'Failed to update team.',
  TEAM_DELETION_FAILED: 'Failed to delete team.',
  TEAM_MEMBER_ADDITION_FAILED: 'Failed to add team member.',
  TEAM_MEMBER_REMOVAL_FAILED: 'Failed to remove team member.',
  TEAM_ROLE_CHANGE_FAILED: 'Failed to change team role.',
  DEPARTMENT_CREATION_FAILED: 'Failed to create department.',
  DEPARTMENT_UPDATE_FAILED: 'Failed to update department.',
  DEPARTMENT_DELETION_FAILED: 'Failed to delete department.',
  DEPARTMENT_MEMBER_ADDITION_FAILED: 'Failed to add department member.',
  DEPARTMENT_MEMBER_REMOVAL_FAILED: 'Failed to remove department member.',
  DEPARTMENT_ROLE_CHANGE_FAILED: 'Failed to change department role.',
  ORGANIZATION_CREATION_FAILED: 'Failed to create organization.',
  ORGANIZATION_UPDATE_FAILED: 'Failed to update organization.',
  ORGANIZATION_DELETION_FAILED: 'Failed to delete organization.',
  ORGANIZATION_MEMBER_ADDITION_FAILED: 'Failed to add organization member.',
  ORGANIZATION_MEMBER_REMOVAL_FAILED: 'Failed to remove organization member.',
  ORGANIZATION_ROLE_CHANGE_FAILED: 'Failed to change organization role.',
  SUBSCRIPTION_CREATION_FAILED: 'Failed to create subscription.',
  SUBSCRIPTION_UPDATE_FAILED: 'Failed to update subscription.',
  SUBSCRIPTION_CANCELLATION_FAILED: 'Failed to cancel subscription.',
  SUBSCRIPTION_RENEWAL_FAILED: 'Failed to renew subscription.',
  SUBSCRIPTION_UPGRADE_FAILED: 'Failed to upgrade subscription.',
  SUBSCRIPTION_DOWNGRADE_FAILED: 'Failed to downgrade subscription.',
  BILLING_INFO_UPDATE_FAILED: 'Failed to update billing info.',
  PAYMENT_METHOD_ADDITION_FAILED: 'Failed to add payment method.',
  PAYMENT_METHOD_REMOVAL_FAILED: 'Failed to remove payment method.',
  INVOICE_GENERATION_FAILED: 'Failed to generate invoice.',
  INVOICE_PAYMENT_FAILED: 'Failed to pay invoice.',
  INVOICE_CANCELLATION_FAILED: 'Failed to cancel invoice.',
  RECEIPT_SEND_FAILED: 'Failed to send receipt.',
  TAX_INFO_UPDATE_FAILED: 'Failed to update tax info.',
  CURRENCY_UPDATE_FAILED: 'Failed to update currency.',
  REGION_UPDATE_FAILED: 'Failed to update region.',
  LANGUAGE_UPDATE_FAILED: 'Failed to update language.',
  TIMEZONE_UPDATE_FAILED: 'Failed to update timezone.',
  DATE_FORMAT_UPDATE_FAILED: 'Failed to update date format.',
  TIME_FORMAT_UPDATE_FAILED: 'Failed to update time format.',
  NUMBER_FORMAT_UPDATE_FAILED: 'Failed to update number format.',
  DECIMAL_SEPARATOR_UPDATE_FAILED: 'Failed to update decimal separator.',
  THOUSANDS_SEPARATOR_UPDATE_FAILED: 'Failed to update thousands separator.',
  FIRST_DAY_OF_WEEK_UPDATE_FAILED: 'Failed to update first day of week.',
  WEEKEND_DAYS_UPDATE_FAILED: 'Failed to update weekend days.',
  WORKING_HOURS_UPDATE_FAILED: 'Failed to update working hours.',
  HOLIDAYS_UPDATE_FAILED: 'Failed to update holidays.',
  BUSINESS_HOURS_UPDATE_FAILED: 'Failed to update business hours.',
  CUSTOM_FIELD_ADDITION_FAILED: 'Failed to add custom field.',
  CUSTOM_FIELD_UPDATE_FAILED: 'Failed to update custom field.',
  CUSTOM_FIELD_DELETION_FAILED: 'Failed to delete custom field.',
  CUSTOM_FIELD_VALUE_ADDITION_FAILED: 'Failed to add custom field value.',
  CUSTOM_FIELD_VALUE_UPDATE_FAILED: 'Failed to update custom field value.',
  CUSTOM_FIELD_VALUE_DELETION_FAILED: 'Failed to delete custom field value.',
  INTEGRATION_ENABLE_FAILED: 'Failed to enable integration.',
  INTEGRATION_DISABLE_FAILED: 'Failed to disable integration.',
  INTEGRATION_CONFIGURATION_FAILED: 'Failed to configure integration.',
  INTEGRATION_TEST_FAILED: 'Failed to test integration.',
  WEBHOOK_CREATION_FAILED: 'Failed to create webhook.',
  WEBHOOK_UPDATE_FAILED: 'Failed to update webhook.',
  WEBHOOK_DELETION_FAILED: 'Failed to delete webhook.',
  WEBHOOK_TRIGGER_FAILED: 'Failed to trigger webhook.',
  API_KEY_CREATION_FAILED: 'Failed to create API key.',
  API_KEY_UPDATE_FAILED: 'Failed to update API key.',
  API_KEY_DELETION_FAILED: 'Failed to delete API key.',
  API_KEY_REVOCATION_FAILED: 'Failed to revoke API key.',
  RATE_LIMIT_UPDATE_FAILED: 'Failed to update rate limit.',
  CACHE_CLEAR_FAILED: 'Failed to clear cache.',
  DATABASE_OPTIMIZATION_FAILED: 'Failed to optimize database.',
  INDEX_CREATION_FAILED: 'Failed to create index.',
  INDEX_DELETION_FAILED: 'Failed to delete index.',
  VIEW_CREATION_FAILED: 'Failed to create view.',
  VIEW_UPDATE_FAILED: 'Failed to update view.',
  VIEW_DELETION_FAILED: 'Failed to delete view.',
  STORED_PROCEDURE_CREATION_FAILED: 'Failed to create stored procedure.',
  STORED_PROCEDURE_UPDATE_FAILED: 'Failed to update stored procedure.',
  STORED_PROCEDURE_DELETION_FAILED: 'Failed to delete stored procedure.',
  TRIGGER_CREATION_FAILED: 'Failed to create trigger.',
  TRIGGER_UPDATE_FAILED: 'Failed to update trigger.',
  TRIGGER_DELETION_FAILED: 'Failed to delete trigger.',
  FUNCTION_CREATION_FAILED: 'Failed to create function.',
  FUNCTION_UPDATE_FAILED: 'Failed to update function.',
  FUNCTION_DELETION_FAILED: 'Failed to delete function.',
  PACKAGE_CREATION_FAILED: 'Failed to create package.',
  PACKAGE_UPDATE_FAILED: 'Failed to update package.',
  PACKAGE_DELETION_FAILED: 'Failed to delete package.',
  TYPE_CREATION_FAILED: 'Failed to create type.',
  TYPE_UPDATE_FAILED: 'Failed to update type.',
  TYPE_DELETION_FAILED: 'Failed to delete type.',
  SEQUENCE_CREATION_FAILED: 'Failed to create sequence.',
  SEQUENCE_UPDATE_FAILED: 'Failed to update sequence.',
  SEQUENCE_DELETION_FAILED: 'Failed to delete sequence.',
  SYNONYM_CREATION_FAILED: 'Failed to create synonym.',
  SYNONYM_UPDATE_FAILED: 'Failed to update synonym.',
  SYNONYM_DELETION_FAILED: 'Failed to delete synonym.',
  DATABASE_BACKUP_CREATION_FAILED: 'Failed to create database backup.',
  DATABASE_BACKUP_RESTORE_FAILED: 'Failed to restore database backup.',
  DATABASE_BACKUP_DELETION_FAILED: 'Failed to delete database backup.',
  DATABASE_BACKUP_SCHEDULING_FAILED: 'Failed to schedule database backup.',
  DATABASE_BACKUP_CANCELLATION_FAILED: 'Failed to cancel database backup.',
  DATABASE_RESTORE_FAILED: 'Database restore failed.',
  DATABASE_MIGRATION_FAILED: 'Database migration failed.',
  DATABASE_UPGRADE_FAILED: 'Database upgrade failed.',
  DATABASE_DOWNGRADE_FAILED: 'Database downgrade failed.',
  DATABASE_MAINTENANCE_FAILED: 'Database maintenance failed.',
  DATABASE_OPTIMIZATION_FAILED: 'Database optimization failed.',
  DATABASE_REINDEX_FAILED: 'Database reindex failed.',
  DATABASE_VACUUM_FAILED: 'Database vacuum failed.',
  DATABASE_ANALYZE_FAILED: 'Database analyze failed.',
  DATABASE_STATS_UPDATE_FAILED: 'Failed to update database stats.',
  DATABASE_STATS_RESET_FAILED: 'Failed to reset database stats.',
  DATABASE_LOCKS_CLEAR_FAILED: 'Failed to clear database locks.',
  DATABASE_CONNECTIONS_RESET_FAILED: 'Failed to reset database connections.',
  DATABASE_SESSIONS_KILL_FAILED: 'Failed to kill database sessions.',
  DATABASE_TRANSACTIONS_ROLLBACK_FAILED: 'Failed to rollback database transactions.',
  DATABASE_DEADLOCK_DETECTION_FAILED: 'Failed to detect database deadlocks.',
  DATABASE_DEADLOCK_RESOLUTION_FAILED: 'Failed to resolve database deadlocks.',
  DATABASE_PERFORMANCE_IMPROVEMENT_FAILED: 'Failed to improve database performance.',
  DATABASE_MONITORING_ENABLE_FAILED: 'Failed to enable database monitoring.',
  DATABASE_MONITORING_DISABLE_FAILED: 'Failed to disable database monitoring.',
  DATABASE_ALERT_CREATION_FAILED: 'Failed to create database alert.',
  DATABASE_ALERT_UPDATE_FAILED: 'Failed to update database alert.',
  DATABASE_ALERT_DELETION_FAILED: 'Failed to delete database alert.',
  DATABASE_ALERT_TRIGGER_FAILED: 'Failed to trigger database alert.',
  DATABASE_METRIC_COLLECTION_FAILED: 'Failed to collect database metric.',
  DATABASE_METRIC_ANALYSIS_FAILED: 'Failed to analyze database metric.',
  DATABASE_METRIC_ALERT_FAILED: 'Failed to alert database metric.',
  DATABASE_HEALTH_CHECK_FAILED: 'Database health check failed.',
  DATABASE_REPLICATION_START_FAILED: 'Failed to start database replication.',
  DATABASE_REPLICATION_STOP_FAILED: 'Failed to stop database replication.',
  DATABASE_REPLICATION_RESUME_FAILED: 'Failed to resume database replication.',
  DATABASE_REPLICATION_PAUSE_FAILED: 'Failed to pause database replication.',
  DATABASE_REPLICATION_STATUS_UPDATE_FAILED: 'Failed to update database replication status.',
  DATABASE_REPLICATION_LAG_DETECTION_FAILED: 'Failed to detect database replication lag.',
  DATABASE_REPLICATION_LAG_RESOLUTION_FAILED: 'Failed to resolve database replication lag.',
  DATABASE_REPLICATION_CONSISTENCY_CHECK_FAILED: 'Failed to check database replication consistency.',
  DATABASE_REPLICATION_CONSISTENCY_RESOLUTION_FAILED: 'Failed to resolve database replication consistency check.',
  DATABASE_REPLICATION_PERFORMANCE_IMPROVEMENT_FAILED: 'Failed to improve database replication performance.',
  DATABASE_REPLICATION_MONITORING_ENABLE_FAILED: 'Failed to enable database replication monitoring.',
  DATABASE_REPLICATION_MONITORING_DISABLE_FAILED: 'Failed to disable database replication monitoring.',
  DATABASE_REPLICATION_ALERT_CREATION_FAILED: 'Failed to create database replication alert.',
  DATABASE_REPLICATION_ALERT_UPDATE_FAILED: 'Failed to update database replication alert.',
  DATABASE_REPLICATION_ALERT_DELETION_FAILED: 'Failed to delete database replication alert.',
  DATABASE_REPLICATION_ALERT_TRIGGER_FAILED: 'Failed to trigger database replication alert.',
  DATABASE_REPLICATION_METRIC_COLLECTION_FAILED: 'Failed to collect database replication metric.',
  DATABASE_REPLICATION_METRIC_ANALYSIS_FAILED: 'Failed to analyze database replication metric.',
  DATABASE_REPLICATION_METRIC_ALERT_FAILED: 'Failed to alert database replication metric.',
  DATABASE_REPLICATION_HEALTH_CHECK_FAILED: 'Database replication health check failed.',
  DATABASE_REPLICATION_BACKUP_CREATION_FAILED: 'Failed to create database replication backup.',
  DATABASE_REPLICATION_BACKUP_RESTORE_FAILED: 'Failed to restore database replication backup.',
  DATABASE_REPLICATION_BACKUP_DELETION_FAILED: 'Failed to delete database replication backup.',
  DATABASE_REPLICATION_BACKUP_SCHEDULING_FAILED: 'Failed to schedule database replication backup.',
  DATABASE_REPLICATION_BACKUP_CANCELLATION_FAILED: 'Failed to cancel database replication backup.',
  DATABASE_REPLICATION_RESTORE_FAILED: 'Database replication restore failed.',
  DATABASE_REPLICATION_MIGRATION_FAILED: 'Database replication migration failed.',
  DATABASE_REPLICATION_UPGRADE_FAILED: 'Database replication upgrade failed.',
  DATABASE_REPLICATION_DOWNGRADE_FAILED: 'Database replication downgrade failed.',
  DATABASE_REPLICATION_MAINTENANCE_FAILED: 'Database replication maintenance failed.',
  DATABASE_REPLICATION_OPTIMIZATION_FAILED: 'Database replication optimization failed.',
  DATABASE_REPLICATION_REINDEX_FAILED: 'Database replication reindex failed.',
  DATABASE_REPLICATION_VACUUM_FAILED: 'Database replication vacuum failed.',
  DATABASE_REPLICATION_ANALYZE_FAILED: 'Database replication analyze failed.',
  DATABASE_REPLICATION_STATS_UPDATE_FAILED: 'Failed to update database replication stats.',
  DATABASE_REPLICATION_STATS_RESET_FAILED: 'Failed to reset database replication stats.',
  DATABASE_REPLICATION_LOCKS_CLEAR_FAILED: 'Failed to clear database replication locks.',
  DATABASE_REPLICATION_CONNECTIONS_RESET_FAILED: 'Failed to reset database replication connections.',
  DATABASE_REPLICATION_SESSIONS_KILL_FAILED: 'Failed to kill database replication sessions.',
  DATABASE_REPLICATION_TRANSACTIONS_ROLLBACK_FAILED: 'Failed to rollback database replication transactions.',
  DATABASE_REPLICATION_DEADLOCK_DETECTION_FAILED: 'Failed to detect database replication deadlocks.',
  DATABASE_REPLICATION_DEADLOCK_RESOLUTION_FAILED: 'Failed to resolve database replication deadlocks.',
  DATABASE_REPLICATION_PERFORMANCE_IMPROVEMENT_FAILED: 'Failed to improve database replication performance.',
  DATABASE_REPLICATION_MONITORING_ENABLE_FAILED: 'Failed to enable database replication monitoring.',
  DATABASE_REPLICATION_MONITORING_DISABLE_FAILED: 'Failed to disable database replication monitoring.',
  DATABASE_REPLICATION_ALERT_CREATION_FAILED: 'Failed to create database replication alert.',
  DATABASE_REPLICATION_ALERT_UPDATE_FAILED: 'Failed to update database replication alert.',
  DATABASE_REPLICATION_ALERT_DELETION_FAILED: 'Failed to delete database replication alert.',
  DATABASE_REPLICATION_ALERT_TRIGGER_FAILED: 'Failed to trigger database replication alert.',
  DATABASE_REPLICATION_METRIC_COLLECTION_FAILED: 'Failed to collect database replication metric.',
  DATABASE_REPLICATION_METRIC_ANALYSIS_FAILED: 'Failed to analyze database replication metric.',
  DATABASE_REPLICATION_METRIC_ALERT_FAILED: 'Failed to alert database replication metric.',
  DATABASE_REPLICATION_HEALTH_CHECK_FAILED: 'Database replication health check failed.'
};

// Success messages
export const SUCCESS_MESSAGES = {
  LOGIN_SUCCESS: 'Successfully logged in.',
  LOGOUT_SUCCESS: 'Successfully logged out.',
  REGISTER_SUCCESS: 'Account created successfully.',
  PASSWORD_RESET_SUCCESS: 'Password reset successful.',
  BOOKING_CREATED: 'Booking created successfully.',
  BOOKING_CONFIRMED: 'Booking confirmed successfully.',
  BOOKING_CANCELLED: 'Booking cancelled successfully.',
  BOOKING_COMPLETED: 'Booking completed successfully.',
  REVIEW_SUBMITTED: 'Review submitted successfully.',
  PROFILE_UPDATED: 'Profile updated successfully.',
  PASSWORD_CHANGED: 'Password changed successfully.',
  EMAIL_VERIFIED: 'Email verified successfully.',
  PHONE_VERIFIED: 'Phone verified successfully.',
  NOTIFICATION_ENABLED: 'Notifications enabled successfully.',
  NOTIFICATION_DISABLED: 'Notifications disabled successfully.',
  PUSH_TOKEN_REGISTERED: 'Push token registered successfully.',
  LOCATION_ENABLED: 'Location services enabled successfully.',
  CAMERA_ENABLED: 'Camera access enabled successfully.',
  STORAGE_ENABLED: 'Storage access enabled successfully.',
  MICROPHONE_ENABLED: 'Microphone access enabled successfully.',
  CONTACTS_ENABLED: 'Contacts access enabled successfully.',
  CALENDAR_ENABLED: 'Calendar access enabled successfully.',
  BIOMETRIC_ENABLED: 'Biometric authentication enabled successfully.',
  BIOMETRIC_DISABLED: 'Biometric authentication disabled successfully.',
  ACCOUNT_VERIFIED: 'Account verified successfully.',
  ACCOUNT_SUSPENDED: 'Account suspended successfully.',
  ACCOUNT_REINSTATED: 'Account reinstated successfully.',
  VENUE_CREATED: 'Venue created successfully.',
  VENUE_UPDATED: 'Venue updated successfully.',
  VENUE_DELETED: 'Venue deleted successfully.',
  VENUE_APPROVED: 'Venue approved successfully.',
  VENUE_REJECTED: 'Venue rejected successfully.',
  PROVIDER_CREATED: 'Provider created successfully.',
  PROVIDER_UPDATED: 'Provider updated successfully.',
  PROVIDER_APPROVED: 'Provider approved successfully.',
  PROVIDER_REJECTED: 'Provider rejected successfully.',
  SERVICE_ADDED: 'Service added successfully.',
  SERVICE_UPDATED: 'Service updated successfully.',
  SERVICE_DELETED: 'Service deleted successfully.',
  STAFF_ADDED: 'Staff member added successfully.',
  STAFFUPDATED: 'Staff member updated successfully.',
  STAFF_DELETED: 'Staff member deleted successfully.',
  AVAILABILITY_UPDATED: 'Availability updated successfully.',
  OPENING_HOURS_UPDATED: 'Opening hours updated successfully.',
  IMAGE_UPLOADED: 'Image uploaded successfully.',
  IMAGE_DELETED: 'Image deleted successfully.',
  PAYMENT_SUCCESS: 'Payment successful.',
  REFUND_SUCCESS: 'Refund successful.',
  CANCELLATION_SUCCESS: 'Cancellation successful.',
  RESCHEDULE_SUCCESS: 'Reschedule successful.',
  REMINDER_SET: 'Reminder set successfully.',
  REMINDER_CANCELLED: 'Reminder cancelled successfully.',
  NOTIFICATION_SENT: 'Notification sent successfully.',
  EMAIL_SENT: 'Email sent successfully.',
  SMS_SENT: 'SMS sent successfully.',
  PUSH_SENT: 'Push notification sent successfully.',
  INVITE_SENT: 'Invite sent successfully.',
  INVITE_ACCEPTED: 'Invite accepted successfully.',
  INVITE_DECLINED: 'Invite declined successfully.',
  FOLLOW_SUCCESS: 'Follow successful.',
  UNFOLLOW_SUCCESS: 'Unfollow successful.',
  LIKE_SUCCESS: 'Like successful.',
  UNLIKE_SUCCESS: 'Unlike successful.',
  SHARE_SUCCESS: 'Share successful.',
  DOWNLOAD_SUCCESS: 'Download successful.',
  UPLOAD_SUCCESS: 'Upload successful.',
  SAVE_SUCCESS: 'Save successful.',
  DELETE_SUCCESS: 'Delete successful.',
  ARCHIVE_SUCCESS: 'Archive successful.',
  RESTORE_SUCCESS: 'Restore successful.',
  DUPLICATE_SUCCESS: 'Duplicate successful.',
  EXPORT_SUCCESS: 'Export successful.',
  IMPORT_SUCCESS: 'Import successful.',
  SYNC_SUCCESS: 'Sync successful.',
  BACKUP_SUCCESS: 'Backup successful.',
  RESTORE_FROM_BACKUP_SUCCESS: 'Restore from backup successful.',
  UPDATE_AVAILABLE: 'Update available.',
  UPDATE_INSTALLED: 'Update installed successfully.',
  FEATURE_ENABLED: 'Feature enabled successfully.',
  FEATURE_DISABLED: 'Feature disabled successfully.',
  THEME_CHANGED: 'Theme changed successfully.',
  LANGUAGE_CHANGED: 'Language changed successfully.',
  CURRENCY_CHANGED: 'Currency changed successfully.',
  REGION_CHANGED: 'Region changed successfully.',
  TIMEZONE_CHANGED: 'Timezone changed successfully.',
  NOTIFICATION_SETTINGS_UPDATED: 'Notification settings updated successfully.',
  PRIVACY_SETTINGS_UPDATED: 'Privacy settings updated successfully.',
  SECURITY_SETTINGS_UPDATED: 'Security settings updated successfully.',
  ACCOUNT_SETTINGS_UPDATED: 'Account settings updated successfully.',
  APP_SETTINGS_UPDATED: 'App settings updated successfully.',
  FEEDBACK_SUBMITTED: 'Feedback submitted successfully.',
  REPORT_SUBMITTED: 'Report submitted successfully.',
  SUPPORT_TICKET_CREATED: 'Support ticket created successfully.',
  SUPPORT_TICKETUPDATED: 'Support ticket updated successfully.',
  SUPPORT_TICKET_CLOSED: 'Support ticket closed successfully.',
  FAQ_VIEWED: 'FAQ viewed successfully.',
  TUTORIAL_COMPLETED: 'Tutorial completed successfully.',
  ONBOARDING_COMPLETED: 'Onboarding completed successfully.',
  WELCOME_MESSAGE: 'Welcome to ZANA!',
  FEATURE_INTRO: 'New feature available!',
  PROMOTION_APPLIED: 'Promotion applied successfully.',
  COUPON_APPLIED: 'Coupon applied successfully.',
  DISCOUNT_APPLIED: 'Discount applied successfully.',
  REWARD_EARNED: 'Reward earned successfully.',
  LEVEL_UP: 'Level up!',
  BADGE_EARNED: 'Badge earned successfully.',
  ACHIEVEMENT_UNLOCKED: 'Achievement unlocked!',
  MILESTONE_REACHED: 'Milestone reached!',
  GOAL_ACHIEVED: 'Goal achieved!',
  CHALLENGE_COMPLETED: 'Challenge completed!',
  STREAK_CONTINUED: 'Streak continued!',
  RECORD_BROKEN: 'Record broken!',
  PERSONAL_BEST: 'Personal best!',
  FIRST_TIME: 'First time!',
  WELCOME_BACK: 'Welcome back!',
  THANK_YOU: 'Thank you!',
  APPRECIATION: 'We appreciate you!',
  LOYALTY_REWARDED: 'Loyalty rewarded!',
  REFERRAL_SUCCESS: 'Referral successful!',
  FRIEND_JOINED: 'Friend joined!',
  GROUP_CREATED: 'Group created successfully.',
  GROUP_JOINED: 'Group joined successfully.',
  GROUP_LEFT: 'Group left successfully.',
  GROUP_DELETED: 'Group deleted successfully.',
  CHAT_STARTED: 'Chat started successfully.',
  MESSAGE_SENT: 'Message sent successfully.',
  MESSAGE_DELETED: 'Message deleted successfully.',
  CONVERSATION_ARCHIVED: 'Conversation archived successfully.',
  CONVERSATION_UNARCHIVED: 'Conversation unarchived successfully.',
  BLOCK_USER: 'User blocked successfully.',
  UNBLOCK_USER: 'User unblocked successfully.',
  REPORT_USER: 'User reported successfully.',
  MUTE_USER: 'User muted successfully.',
  UNMUTE_USER: 'User unmuted successfully.',
  PIN_MESSAGE: 'Message pinned successfully.',
  UNPIN_MESSAGE: 'Message unpinned successfully.',
  STAR_MESSAGE: 'Message starred successfully.',
  UNSTAR_MESSAGE: 'Message unstarred successfully.',
  REACTION_ADDED: 'Reaction added successfully.',
  REACTION_REMOVED: 'Reaction removed successfully.',
  EMOJI_ADDED: 'Emoji added successfully.',
  EMOJI_REMOVED: 'Emoji removed successfully.',
  STICKER_ADDED: 'Sticker added successfully.',
  STICKER_REMOVED: 'Sticker removed successfully.',
  GIF_SENT: 'GIF sent successfully.',
  FILE_SENT: 'File sent successfully.',
  VOICE_MESSAGE_SENT: 'Voice message sent successfully.',
  VIDEO_CALL_STARTED: 'Video call started successfully.',
  VIDEO_CALL_ENDED: 'Video call ended successfully.',
  AUDIO_CALL_STARTED: 'Audio call started successfully.',
  AUDIO_CALL_ENDED: 'Audio call ended successfully.',
  SCREEN_SHARE_STARTED: 'Screen share started successfully.',
  SCREEN_SHARE_ENDED: 'Screen share ended successfully.',
  RECORDING_STARTED: 'Recording started successfully.',
  RECORDING_ENDED: 'Recording ended successfully.',
  LIVE_STREAM_STARTED: 'Live stream started successfully.',
  LIVE_STREAM_ENDED: 'Live stream ended successfully.',
  BROADCAST_STARTED: 'Broadcast started successfully.',
  BROADCAST_ENDED: 'Broadcast ended successfully.',
  EVENT_CREATED: 'Event created successfully.',
  EVENTUPDATED: 'Event updated successfully.',
  EVENT_DELETED: 'Event deleted successfully.',
  EVENT_JOINED: 'Event joined successfully.',
  EVENT_LEFT: 'Event left successfully.',
  EVENT_CANCELLED: 'Event cancelled successfully.',
  EVENT_RESCHEDULED: 'Event rescheduled successfully.',
  REMINDER_ADDED: 'Reminder added successfully.',
  REMINDERUPDATED: 'Reminder updated successfully.',
  REMINDER_DELETED: 'Reminder deleted successfully.',
  REMINDER_COMPLETED: 'Reminder completed successfully.',
  TASK_CREATED: 'Task created successfully.',
  TASKUPDATED: 'Task updated successfully.',
  TASK_DELETED: 'Task deleted successfully.',
  TASK_COMPLETED: 'Task completed successfully.',
  TASK_ASSIGNED: 'Task assigned successfully.',
  TASK_UNASSIGNED: 'Task unassigned successfully.',
  PROJECT_CREATED: 'Project created successfully.',
  PROJECTUPDATED: 'Project updated successfully.',
  PROJECT_DELETED: 'Project deleted successfully.',
  PROJECT_COMPLETED: 'Project completed successfully.',
  PROJECT_ARCHIVED: 'Project archived successfully.',
  PROJECT_RESTORED: 'Project restored successfully.',
  TEAM_CREATED: 'Team created successfully.',
  TEAMUPDATED: 'Team updated successfully.',
  TEAM_DELETED: 'Team deleted successfully.',
  TEAM_MEMBER_ADDED: 'Team member added successfully.',
  TEAM_MEMBER_REMOVED: 'Team member removed successfully.',
  TEAM_ROLE_CHANGED: 'Team role changed successfully.',
  DEPARTMENT_CREATED: 'Department created successfully.',
  DEPARTMENTUPDATED: 'Department updated successfully.',
  DEPARTMENT_DELETED: 'Department deleted successfully.',
  DEPARTMENT_MEMBER_ADDED: 'Department member added successfully.',
  DEPARTMENT_MEMBER_REMOVED: 'Department member removed successfully.',
  DEPARTMENT_ROLE_CHANGED: 'Department role changed successfully.',
  ORGANIZATION_CREATED: 'Organization created successfully.',
  ORGANIZATIONUPDATED: 'Organization updated successfully.',
  ORGANIZATION_DELETED: 'Organization deleted successfully.',
  ORGANIZATION_MEMBER_ADDED: 'Organization member added successfully.',
  ORGANIZATION_MEMBER_REMOVED: 'Organization member removed successfully.',
  ORGANIZATION_ROLE_CHANGED: 'Organization role changed successfully.',
  SUBSCRIPTION_CREATED: 'Subscription created successfully.',
  SUBSCRIPTIONUPDATED: 'Subscription updated successfully.',
  SUBSCRIPTION_CANCELLED: 'Subscription cancelled successfully.',
  SUBSCRIPTION_RENEWED: 'Subscription renewed successfully.',
  SUBSCRIPTION_UPGRADED: 'Subscription upgraded successfully.',
  SUBSCRIPTION_DOWNGRADED: 'Subscription downgraded successfully.',
  BILLING_INFOUPDATED: 'Billing info updated successfully.',
  PAYMENT_METHOD_ADDED: 'Payment method added successfully.',
  PAYMENT_METHOD_REMOVED: 'Payment method removed successfully.',
  INVOICE_GENERATED: 'Invoice generated successfully.',
  INVOICE_PAID: 'Invoice paid successfully.',
  INVOICE_CANCELLED: 'Invoice cancelled successfully.',
  RECEIPT_SENT: 'Receipt sent successfully.',
  TAX_INFOUPDATED: 'Tax info updated successfully.',
  CURRENCYUPDATED: 'Currency updated successfully.',
  REGIONUPDATED: 'Region updated successfully.',
  LANGUAGEUPDATED: 'Language updated successfully.',
  TIMEZONEUPDATED: 'Timezone updated successfully.',
  DATE_FORMATUPDATED: 'Date format updated successfully.',
  TIME_FORMATUPDATED: 'Time format updated successfully.',
  NUMBER_FORMATUPDATED: 'Number format updated successfully.',
  DECIMAL_SEPARATORUPDATED: 'Decimal separator updated successfully.',
  THOUSANDS_SEPARATORUPDATED: 'Thousands separator updated successfully.',
  FIRST_DAY_OF_WEEKUPDATED: 'First day of week updated successfully.',
  WEEKEND_DAYSUPDATED: 'Weekend days updated successfully.',
  WORKING_HOURSUPDATED: 'Working hours updated successfully.',
  HOLIDAYSUPDATED: 'Holidays updated successfully.',
  BUSINESS_HOURSUPDATED: 'Business hours updated successfully.',
  CUSTOM_FIELD_ADDED: 'Custom field added successfully.',
  CUSTOM_FIELDUPDATED: 'Custom field updated successfully.',
  CUSTOM_FIELD_DELETED: 'Custom field deleted successfully.',
  CUSTOM_FIELD_VALUE_ADDED: 'Custom field value added successfully.',
  CUSTOM_FIELD_VALUEUPDATED: 'Custom field value updated successfully.',
  CUSTOM_FIELD_VALUE_DELETED: 'Custom field value deleted successfully.',
  INTEGRATION_ENABLED: 'Integration enabled successfully.',
  INTEGRATION_DISABLED: 'Integration disabled successfully.',
  INTEGRATION_CONFIGURED: 'Integration configured successfully.',
  INTEGRATION_TESTED: 'Integration tested successfully.',
  WEBHOOK_CREATED: 'Webhook created successfully.',
  WEBHOOKUPDATED: 'Webhook updated successfully.',
  WEBHOOK_DELETED: 'Webhook deleted successfully.',
  WEBHOOK_TRIGGERED: 'Webhook triggered successfully.',
  API_KEY_CREATED: 'API key created successfully.',
  API_KEYUPDATED: 'API key updated successfully.',
  API_KEY_DELETED: 'API key deleted successfully.',
  API_KEY_REVOKED: 'API key revoked successfully.',
  RATE_LIMITUPDATED: 'Rate limit updated successfully.',
  CACHE_CLEARED: 'Cache cleared successfully.',
  DATABASE_OPTIMIZED: 'Database optimized successfully.',
  INDEX_CREATED: 'Index created successfully.',
  INDEX_DELETED: 'Index deleted successfully.',
  VIEW_CREATED: 'View created successfully.',
  VIEWUPDATED: 'View updated successfully.',
  VIEW_DELETED: 'View deleted successfully.',
  STORED_PROCEDURE_CREATED: 'Stored procedure created successfully.',
  STORED_PROCEDUREUPDATED: 'Stored procedure updated successfully.',
  STORED_PROCEDURE_DELETED: 'Stored procedure deleted successfully.',
  TRIGGER_CREATED: 'Trigger created successfully.',
  TRIGGERUPDATED: 'Trigger updated successfully.',
  TRIGGER_DELETED: 'Trigger deleted successfully.',
  FUNCTION_CREATED: 'Function created successfully.',
  FUNCTIONUPDATED: 'Function updated successfully.',
  FUNCTION_DELETED: 'Function deleted successfully.',
  PACKAGE_CREATED: 'Package created successfully.',
  PACKAGEUPDATED: 'Package updated successfully.',
  PACKAGE_DELETED: 'Package deleted successfully.',
  TYPE_CREATED: 'Type created successfully.',
  TYPEUPDATED: 'Type updated successfully.',
  TYPE_DELETED: 'Type deleted successfully.',
  SEQUENCE_CREATED: 'Sequence created successfully.',
  SEQUENCEUPDATED: 'Sequence updated successfully.',
  SEQUENCE_DELETED: 'Sequence deleted successfully.',
  SYNONYM_CREATED: 'Synonym created successfully.',
  SYNONYMUPDATED: 'Synonym updated successfully.',
  SYNONYM_DELETED: 'Synonym deleted successfully.',
  DATABASE_BACKUP_CREATED: 'Database backup created successfully.',
  DATABASE_BACKUP_RESTORED: 'Database backup restored successfully.',
  DATABASE_BACKUP_DELETED: 'Database backup deleted successfully.',
  DATABASE_BACKUP_SCHEDULED: 'Database backup scheduled successfully.',
  DATABASE_BACKUP_CANCELLED: 'Database backup cancelled successfully.',
  DATABASE_RESTORE_COMPLETED: 'Database restore completed successfully.',
  DATABASE_MIGRATION_STARTED: 'Database migration started successfully.',
  DATABASE_MIGRATION_COMPLETED: 'Database migration completed successfully.',
  DATABASE_UPGRADE_STARTED: 'Database upgrade started successfully.',
  DATABASE_UPGRADE_COMPLETED: 'Database upgrade completed successfully.',
  DATABASE_DOWNGRADE_STARTED: 'Database downgrade started successfully.',
  DATABASE_DOWNGRADE_COMPLETED: 'Database downgrade completed successfully.',
  DATABASE_MAINTENANCE_STARTED: 'Database maintenance started successfully.',
  DATABASE_MAINTENANCE_COMPLETED: 'Database maintenance completed successfully.',
  DATABASE_OPTIMIZATION_STARTED: 'Database optimization started successfully.',
  DATABASE_OPTIMIZATION_COMPLETED: 'Database optimization completed successfully.',
  DATABASE_REINDEX_STARTED: 'Database reindex started successfully.',
  DATABASE_REINDEX_COMPLETED: 'Database reindex completed successfully.',
  DATABASE_VACUUM_STARTED: 'Database vacuum started successfully.',
  DATABASE_VACUUM_COMPLETED: 'Database vacuum completed successfully.',
  DATABASE_ANALYZE_STARTED: 'Database analyze started successfully.',
  DATABASE_ANALYZE_COMPLETED: 'Database analyze completed successfully.',
  DATABASE_STATSUPDATED: 'Database stats updated successfully.',
  DATABASE_STATS_RESET: 'Database stats reset successfully.',
  DATABASE_LOCKS_CLEARED: 'Database locks cleared successfully.',
  DATABASE_CONNECTIONS_RESET: 'Database connections reset successfully.',
  DATABASE_SESSIONS_KILLED: 'Database sessions killed successfully.',
  DATABASE_TRANSACTIONS_ROLLED_BACK: 'Database transactions rolled back successfully.',
  DATABASE_DEADLOCKS_DETECTED: 'Database deadlocks detected.',
  DATABASE_DEADLOCKS_RESOLVED: 'Database deadlocks resolved successfully.',
  DATABASE_PERFORMANCE_IMPROVED: 'Database performance improved successfully.',
  DATABASE_MONITORING_ENABLED: 'Database monitoring enabled successfully.',
  DATABASE_MONITORING_DISABLED: 'Database monitoring disabled successfully.',
  DATABASE_ALERT_CREATED: 'Database alert created successfully.',
  DATABASE_ALERTUPDATED: 'Database alert updated successfully.',
  DATABASE_ALERT_DELETED: 'Database alert deleted successfully.',
  DATABASE_ALERT_TRIGGERED: 'Database alert triggered successfully.',
  DATABASE_METRIC_COLLECTED: 'Database metric collected successfully.',
  DATABASE_METRIC_ANALYZED: 'Database metric analyzed successfully.',
  DATABASE_METRIC_ALERTED: 'Database metric alerted successfully.',
  DATABASE_HEALTH_CHECK_PASSED: 'Database health check passed successfully.',
  DATABASE_REPLICATION_STARTED: 'Database replication started successfully.',
  DATABASE_REPLICATION_STOPPED: 'Database replication stopped successfully.',
  DATABASE_REPLICATION_RESUMED: 'Database replication resumed successfully.',
  DATABASE_REPLICATION_PAUSED: 'Database replication paused successfully.',
  DATABASE_REPLICATION_STATUSUPDATED: 'Database replication status updated successfully.',
  DATABASE_REPLICATION_LAG_DETECTED: 'Database replication lag detected.',
  DATABASE_REPLICATION_LAG_RESOLVED: 'Database replication lag resolved successfully.',
  DATABASE_REPLICATION_CONSISTENCY_CHECKED: 'Database replication consistency checked successfully.',
  DATABASE_REPLICATION_CONSISTENCY_RESOLVED: 'Database replication consistency check resolved successfully.',
  DATABASE_REPLICATION_PERFORMANCE_IMPROVED: 'Database replication performance improved successfully.',
  DATABASE_REPLICATION_MONITORING_ENABLED: 'Database replication monitoring enabled successfully.',
  DATABASE_REPLICATION_MONITORING_DISABLED: 'Database replication monitoring disabled successfully.',
  DATABASE_REPLICATION_ALERT_CREATED: 'Database replication alert created successfully.',
  DATABASE_REPLICATION_ALERTUPDATED: 'Database replication alert updated successfully.',
  DATABASE_REPLICATION_ALERT_DELETED: 'Database replication alert deleted successfully.',
  DATABASE_REPLICATION_ALERT_TRIGGERED: 'Database replication alert triggered successfully.',
  DATABASE_REPLICATION_METRIC_COLLECTED: 'Database replication metric collected successfully.',
  DATABASE_REPLICATION_METRIC_ANALYZED: 'Database replication metric analyzed successfully.',
  DATABASE_REPLICATION_METRIC_ALERTED: 'Database replication metric alerted successfully.',
  DATABASE_REPLICATION_HEALTH_CHECK_PASSED: 'Database replication health check passed successfully.',
  DATABASE_REPLICATION_BACKUP_CREATED: 'Database replication backup created successfully.',
  DATABASE_REPLICATION_BACKUP_RESTORED: 'Database replication backup restored successfully.',
  DATABASE_REPLICATION_BACKUP_DELETED: 'Database replication backup deleted successfully.',
  DATABASE_REPLICATION_BACKUP_SCHEDULED: 'Database replication backup scheduled successfully.',
  DATABASE_REPLICATION_BACKUP_CANCELLED: 'Database replication backup cancelled successfully.',
  DATABASE_REPLICATION_RESTORE_COMPLETED: 'Database replication restore completed successfully.',
  DATABASE_REPLICATION_MIGRATION_STARTED: 'Database replication migration started successfully.',
  DATABASE_REPLICATION_MIGRATION_COMPLETED: 'Database replication migration completed successfully.',
  DATABASE_REPLICATION_UPGRADE_STARTED: 'Database replication upgrade started successfully.',
  DATABASE_REPLICATION_UPGRADE_COMPLETED: 'Database replication upgrade completed successfully.',
  DATABASE_REPLICATION_DOWNGRADE_STARTED: 'Database replication downgrade started successfully.',
  DATABASE_REPLICATION_DOWNGRADE_COMPLETED: 'Database replication downgrade completed successfully.',
  DATABASE_REPLICATION_MAINTENANCE_STARTED: 'Database replication maintenance started successfully.',
  DATABASE_REPLICATION_MAINTENANCE_COMPLETED: 'Database replication maintenance completed successfully.',
  DATABASE_REPLICATION_OPTIMIZATION_STARTED: 'Database replication optimization started successfully.',
  DATABASE_REPLICATION_OPTIMIZATION_COMPLETED: 'Database replication optimization completed successfully.',
  DATABASE_REPLICATION_REINDEX_STARTED: 'Database replication reindex started successfully.',
  DATABASE_REPLICATION_REINDEX_COMPLETED: 'Database replication reindex completed successfully.',
  DATABASE_REPLICATION_VACUUM_STARTED: 'Database replication vacuum started successfully.',
  DATABASE_REPLICATION_VACUUM_COMPLETED: 'Database replication vacuum completed successfully.',
  DATABASE_REPLICATION_ANALYZE_STARTED: 'Database replication analyze started successfully.',
  DATABASE_REPLICATION_ANALYZE_COMPLETED: 'Database replication analyze completed successfully.',
  DATABASE_REPLICATION_STATSUPDATED: 'Database replication stats updated successfully.',
  DATABASE_REPLICATION_STATS_RESET: 'Database replication stats reset successfully.',
  DATABASE_REPLICATION_LOCKS_CLEARED: 'Database replication locks cleared successfully.',
  DATABASE_REPLICATION_CONNECTIONS_RESET: 'Database replication connections reset successfully.',
  DATABASE_REPLICATION_SESSIONS_KILLED: 'Database replication sessions killed successfully.',
  DATABASE_REPLICATION_TRANSACTIONS_ROLLED_BACK: 'Database replication transactions rolled back successfully.',
  DATABASE_REPLICATION_DEADLOCKS_DETECTED: 'Database replication deadlocks detected.',
  DATABASE_REPLICATION_DEADLOCKS_RESOLVED: 'Database replication deadlocks resolved successfully.',
  DATABASE_REPLICATION_PERFORMANCE_IMPROVED: 'Database replication performance improved successfully.',
  DATABASE_REPLICATION_MONITORING_ENABLED: 'Database replication monitoring enabled successfully.',
  DATABASE_REPLICATION_MONITORING_DISABLED: 'Database replication monitoring disabled successfully.',
  DATABASE_REPLICATION_ALERT_CREATED: 'Database replication alert created successfully.',
  DATABASE_REPLICATION_ALERTUPDATED: 'Database replication alert updated successfully.',
  DATABASE_REPLICATION_ALERT_DELETED: 'Database replication alert deleted successfully.',
  DATABASE_REPLICATION_ALERT_TRIGGERED: 'Database replication alert triggered successfully.',
  DATABASE_REPLICATION_METRIC_COLLECTED: 'Database replication metric collected successfully.',
  DATABASE_REPLICATION_METRIC_ANALYZED: 'Database replication metric analyzed successfully.',
  DATABASE_REPLICATION_METRIC_ALERTED: 'Database replication metric alerted successfully.',
  DATABASE_REPLICATION_HEALTH_CHECK_PASSED: 'Database replication health check passed successfully.'
};
